version: 2
project_name: modbus-console-core

builds:
  - id: core
    dir: core
    main: ./cmd/modbus-console-core
    binary: modbus-console-core
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: core
    ids: [core]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
